server:
  port: 9995
  context-path: /
  tomcat:
    uri-encoding: utf-8
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles: 
    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  dubbo:
    application:
      name: shopRabbit
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: com.zscat
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.zscat.*.domain
qiniu:
  accessKey: AMJ_CEvgX1eUYtSwC1ioo_WnmR73ufqYYmwrrPDV
  secretKey: 1iUDYRKdibiVP-WZLrGoErtdWWCqYWXjKUbQtAYQ
  bucketName:  j5shop
  basePath: http://p0bt2oaom.bkt.clouddn.com/
